openapi: '3.0.2'
info:
  title: Prison Break API Documentation
  version: '1.0'
servers:
  - url: https://prisonbreakapi.me/api/

paths:
  /episodes:
    get:
      summary: Get all episodes.
      description: Fetches all episodes from the database.
      responses:
        '200':
          description: Data fetched successfully.
        '404':
          description: Data not found.
        '502':
          description: Server is down.

    post:
      summary: Add an episode.
      description: Uses data from message body and adds a new episode.
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              type: object
              required:
                - name
                - position
                - mainCast
                - summary
              properties:
                name:
                  type: string
                position:
                  type: string
                mainCast:
                  type: string
                summary:
                  type: string
      responses:
        '201':
          description: Data added successfully.
        '400':
          description: Bad request.
        '401':
          description: Not authorized.
        '502':
          description: You probably submitted an empty form.

  /episodes/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema: 
          type: integer
          minimum: 1
          maximum: 11

    get:
      summary: Get a single episode by id.
      description: Fetches a single episode from the database by adding the id to the base URL.
      responses:
        '200':
          description: Data fetched successfully.
        '404':
          description: Data not found.
        '502':
          description: Server is down.

  /characters:
    get:
      summary: Get all characters.
      description: Fetches all characters from database.
      responses:
        '200':
          description: Data fetched successfully.
        '404':
          description: Data not found.
        '502':
          description: Server is down.

    post:
      summary: Add a character.
      description: Uses data from message body and adds a new character.
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              type: object
              required:
                - name
                - story
                - quotes
                - firstAppearance
                - lastAppearance
              properties:
                name:
                  type: string
                nickname:
                  type: string
                story:
                  type: string
                abilities:
                  type: string
                quotes:
                  type: string
                crimes:
                  type: string
                IncarceratedIn:
                  type: string
                firstAppearance:
                  type: string
                lastAppearance:
                  type: string
                kils:
                  type: string
      responses:
        '201':
          description: Data added successfully.
        '400':
          description: Bad request.
        '401':
          description: Not authorized.
        '502':
          description: You probably submitted an empty form.
          

  /characters/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema: 
          type: integer
          minimum: 1
          maximum: 11

    get:
      summary: Get a single character by id.
      description: Fetches a single character from the database by adding the id to the base URL.
      responses:
        '200':
          description: Data fetched successfully.
        '404':
          description: Data not found.
        '502':
          description: Server is down.

  /locations:
    get:
      summary: Get all locations.
      description: Fetches all locations from database.
      responses:
        '200':
          description: Data fetched successfully.
        '404':
          description: Data not found.
        '502':
          description: Server is down.

  /locations/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema: 
          type: integer
          minimum: 1
          maximum: 8

    get:
      summary: Get a single location by id.
      description: Fetches a single location from the database by adding the id to the base URL.
      responses:
        '200':
          description: Data fetched successfully.
        '404':
          description: Data not found.
        '502':
          description: Server is down.

  /codes:
    get:
      summary: Get all codes.
      description: Fethces all codes from the database.
      responses:
        '200':
          description: Data fetched successfully.
        '404':
          description: Data not found.
        '502':
          description: Server is down.

  /codes/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema: 
          type: integer
          minimum: 1
          maximum: 11

    get:
      summary: Get a single code by id.
      description: Fetches a single code from the database by adding the id to the base URL.
      responses:
        '200':
          description: Data fetched successfully.
        '404':
          description: Data not found.
        '502':
          description: Server is down.